/*
 * generated by Xtext
 */
package com.kilic.xexpr.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class XexprUiModule extends com.kilic.xexpr.dsl.ui.AbstractXexprUiModule {
	public XexprUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
