/*
 * generated by Xtext
 */
package com.kilic.xmake.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class XmakeUiModule extends com.kilic.xmake.dsl.ui.AbstractXmakeUiModule {
	public XmakeUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
