/*
 * generated by Xtext
 */
package com.kilic.xmake.dsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class XmakeRuntimeModule extends com.kilic.xmake.dsl.AbstractXmakeRuntimeModule {

}
