/*
 * generated by Xtext
 */
package com.kilic.xmake.dsl;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class XmakeStandaloneSetup extends XmakeStandaloneSetupGenerated{

	public static void doSetup() {
		new XmakeStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

