/*
 * generated by Xtext
 */
package com.kilic.xmake.dsl.scoping

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 *
 */
class XmakeScopeProvider extends com.kilic.xexpr.dsl.scoping.XexprScopeProvider {

}
