/*
 * generated by Xtext
 */
package com.kilic.xexpr.dsl.ui.contentassist

import com.kilic.xexpr.dsl.ui.contentassist.AbstractXexprProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class XexprProposalProvider extends AbstractXexprProposalProvider {
}
