/*
 * generated by Xtext
 */
package com.kilic.xmake.dsl.ui.contentassist

import com.kilic.xmake.dsl.ui.contentassist.AbstractXmakeProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class XmakeProposalProvider extends AbstractXmakeProposalProvider {
}
